import { useEffect, useState } from 'react';
import { qrApi } from '../../cloud/cloudClient';
import { QrAdminApi, type QrBranch } from '../../cloud/qrAdminClient';
type Stock={branchId:string;items:Array<{itemId:string;name:string;stockQuantity:number|null;source:string}>};
export function QrCountedStock({showToast}:{showToast:(message:string)=>void}){
 const [branches,setBranches]=useState<QrBranch[]>([]),[branch,setBranch]=useState(''),[stock,setStock]=useState<Stock|null>(null),[itemId,setItemId]=useState(''),[quantity,setQuantity]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>setStock(await qrApi<Stock>('/api/v1/restaurant/qr/advanced/stock?branchId='+encodeURIComponent(branch)));
 useEffect(()=>{let active=true;QrAdminApi.branches().then(rows=>{if(active){setBranches(rows);setBranch(rows.length===1?rows[0].id:'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 useEffect(()=>{if(!branch)return;let active=true;qrApi<Stock>('/api/v1/restaurant/qr/advanced/stock?branchId='+encodeURIComponent(branch)).then(s=>{if(active)setStock(s);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[branch]);
 return <section className="mt-5 rounded-xl border bg-[#fbf8f4] p-4"><h4 className="font-bold">Counted portions for this branch</h4><p className="mt-1 text-xs text-slate-500">Optional exact counts for ready-to-sell dishes. Ingredient recipes continue through the existing inventory ledger. Enable counted stock reservations above to protect simultaneous QR checkouts.</p><div className="my-3 grid gap-3 sm:grid-cols-3"><label className="text-xs">Branch<select className="mt-1 w-full rounded-xl border bg-white p-3" value={branch} onChange={e=>{setBranch(e.target.value);setStock(null);setItemId('');}}><option value="">Choose branch...</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="text-xs">Dish<select className="mt-1 w-full rounded-xl border bg-white p-3" value={itemId} onChange={e=>{setItemId(e.target.value);const row=stock?.items.find(i=>i.itemId===e.target.value);setQuantity(row?.stockQuantity===null?'':String(row?.stockQuantity??''));}}><option value="">Choose dish...</option>{stock?.items.map(i=><option key={i.itemId} value={i.itemId}>{i.name} · {i.stockQuantity===null?'Manual availability':i.stockQuantity+' portions'}</option>)}</select></label><label className="text-xs">Current portions (blank = inherit/manual)<input className="mt-1 w-full rounded-xl border bg-white p-3" type="number" min="0" max="1000000" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label></div><button className="rounded-xl bg-jaman-navy px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40" disabled={busy||!branch||!itemId} onClick={async()=>{setBusy(true);setError('');try{await qrApi('/api/v1/menu/branch-overrides',{method:'PUT',body:JSON.stringify({branchId:branch,itemId,stockQuantity:quantity===''?null:Number(quantity)})});await load();showToast('Branch counted stock updated');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Save counted portions</button>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</section>;
}
