import React, { useEffect, useState } from 'react';
import { fetchTenantDashboard, type TenantDashboard } from '../../cloud/cloudClient';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:0,maximumFractionDigits:2}).format(n);
export function BranchBusinessDashboard({branchId}:{branchId:string}) {
  const [period,setPeriod]=useState('TODAY'),[source,setSource]=useState('ALL');
  const [from,setFrom]=useState(new Date().toISOString().slice(0,10)),[to,setTo]=useState(new Date().toISOString().slice(0,10));
  const [data,setData]=useState<TenantDashboard|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
  useEffect(()=>{
    let stopped=false,running=false;
    const load=async()=>{if(running)return;running=true;setBusy(true);try {const next=await fetchTenantDashboard({branchId,period,source,...(period==='CUSTOM'?{from,to}:{})});if(!stopped){setData(next);setError('');}}catch(e){if(!stopped)setError(e instanceof Error?e.message:'Dashboard unavailable');}finally{running=false;if(!stopped)setBusy(false);}};
    setData(null);void load();const interval=setInterval(()=>void load(),15000);
    return()=>{stopped=true;clearInterval(interval);};
  },[branchId,period,source,from,to,refresh]);
  const card='rounded-2xl border border-jaman-border bg-white p-4 sm:p-5 shadow-sm';
  return <section className="space-y-5" aria-label="Branch business dashboard">
    <div className="flex flex-wrap justify-between gap-3 items-center"><div><h1 className="text-2xl sm:text-3xl font-extrabold">Business overview</h1><p className="text-sm text-slate-500">{data?.scope.label??'Loading workspace'} · Confirmed sales, open payments and device health</p></div>
      <div className="flex gap-2 flex-wrap"><select aria-label="Dashboard period" value={period} onChange={e=>setPeriod(e.target.value)} className="rounded-xl border border-jaman-border bg-white p-2"><option value="TODAY">Today</option><option value="YESTERDAY">Yesterday</option><option value="7_DAYS">Last 7 days</option><option value="30_DAYS">Last 30 days</option><option value="THIS_MONTH">This month</option><option value="THIS_YEAR">This year</option><option value="CUSTOM">Custom dates</option></select>
        {period==='CUSTOM'&&<><label className="text-xs">From<input aria-label="Dashboard from date" type="date" value={from} onChange={e=>setFrom(e.target.value)} className="block rounded-xl border p-2"/></label><label className="text-xs">To<input aria-label="Dashboard to date" type="date" value={to} min={from} onChange={e=>setTo(e.target.value)} className="block rounded-xl border p-2"/></label></>}
        <select aria-label="Order source" value={source} onChange={e=>setSource(e.target.value)} className="rounded-xl border border-jaman-border bg-white p-2">{['ALL','POS','CAPTAIN','KIOSK','QR','WHATSAPP','ONLINE'].map(s=><option key={s} value={s}>{s==='ALL'?'All sources':s}</option>)}</select><button className="rounded-xl bg-jaman-navy text-white px-4 py-2 font-bold" disabled={busy} onClick={()=>setRefresh(n=>n+1)}>{busy?'Updating…':'Refresh'}</button></div></div>
    {error&&<div role="alert" className="p-4 rounded-xl bg-amber-50 text-amber-900">{error}{data&&' · Showing the last successful snapshot; totals may have changed.'}</div>}
    {!data&&!error&&<p role="status">Loading consolidated data…</p>}
    {data&&<>
      <div className="grid grid-cols-2 xl:grid-cols-4 gap-3">{[['Net sales',money(data.summary.sales)],['Orders',data.summary.orders],['Average paid order',money(data.summary.averageOrder)],['Awaiting payment',money(data.summary.pendingAmount)]].map(([label,value])=><div className={card} key={label}><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="text-2xl sm:text-3xl font-extrabold mt-3">{value}</p></div>)}</div>
      <p className="text-xs text-slate-500">Gross paid sales {money(data.summary.grossSales)} · Refunds {money(data.summary.refunds)} · {data.summary.pendingPayments} unpaid orders · {data.scope.from} to {data.scope.to} ({data.scope.timezone}) · Updated {new Date(data.generatedAt).toLocaleTimeString()}</p>
      <div className="grid xl:grid-cols-2 gap-4"><div className={card}><h2 className="font-extrabold mb-4">Sales trend</h2><BarChart rows={data.trend.map(p=>({label:p.bucket,value:p.sales}))}/></div><div className={card}><h2 className="font-extrabold mb-4">Sales by source</h2><BarChart rows={data.bySource.map(p=>({label:`${p.source} (${p.orders})`,value:p.sales}))}/></div></div>
      <div className={card}><h2 className="font-extrabold mb-4">Sales by branch</h2><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr className="text-slate-500 border-b"><th className="p-2">Branch</th><th className="p-2">Net sales</th><th className="p-2">Orders</th><th className="p-2">AOV</th><th className="p-2">Online devices</th><th className="p-2">Activated setup</th></tr></thead><tbody>{data.byBranch.map(b=><tr key={b.id} className="border-b"><td className="p-2 font-bold">{b.name}<span className="block text-xs text-slate-500">{b.code} · {b.status}</span></td><td className="p-2">{money(b.sales)}</td><td className="p-2">{b.orders}</td><td className="p-2">{money(b.averageOrder)}</td><td className="p-2">{b.online}/{b.devices}</td><td className="p-2 text-xs">{b.deployedProducts.join(' · ')||'No devices activated'}</td></tr>)}</tbody></table></div>{data.unassigned&&<p className="mt-3 text-amber-800 text-xs">Unassigned legacy orders: {data.unassigned.orders} · {money(data.unassigned.sales)}. Included in restaurant totals; no branch has been guessed.</p>}<p className="text-xs text-slate-500 mt-3">Subscriptions apply to the restaurant. Activated devices and QR codes determine each branch’s setup.</p></div>
      <div className="grid lg:grid-cols-2 gap-4"><div className={card}><h2 className="font-extrabold mb-4">Top items</h2>{!data.topItems.length&&<p className="text-slate-500">No paid items in this period.</p>}{data.topItems.map((i,n)=><div key={`${i.id}-${n}`} className="flex gap-3 justify-between border-b py-3 text-sm"><span>{i.name} <small className="text-slate-500">{i.units} sold</small></span><strong>{money(i.revenue)}</strong></div>)}</div><div className={card}><h2 className="font-extrabold mb-4">Device health</h2><div className="grid grid-cols-2 gap-3">{data.deviceCounts.map(d=><div key={d.type} className="rounded-xl bg-jaman-cream p-3"><strong>{d.type}</strong><p className="text-sm">{d.online}/{d.total} online</p></div>)}</div><p className="text-xs text-slate-500 mt-3">Online requires a recent heartbeat. Registered devices are not assumed connected.</p></div></div>
      <div className={card}><h2 className="font-extrabold mb-4">Alerts</h2>{!data.alerts.length?<p className="text-emerald-700">No device or stock alerts.</p>:data.alerts.map((a,n)=><div key={n} className="py-2 border-b flex flex-wrap justify-between gap-2 text-sm"><strong>{a.title}</strong><span className="text-amber-800">{a.detail}</span></div>)}</div>
      <div className={card}><h2 className="font-extrabold mb-4">Recent orders</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500">{['Order','Branch','Source','Status','Payment','Amount'].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{data.recentOrders.map(o=><tr key={o.externalOrderId} className="border-b"><td className="p-2 font-bold">{o.tokenNumber??o.orderNumber??o.externalOrderId}</td><td className="p-2">{o.branchName}</td><td className="p-2">{o.source}</td><td className="p-2">{o.status}</td><td className="p-2">{o.paymentStatus??'Pending'}</td><td className="p-2">{money(o.total)}</td></tr>)}</tbody></table></div></div>
    </>}
  </section>;
}
function BarChart({rows}:{rows:{label:string;value:number}[]}) {const max=Math.max(1,...rows.map(r=>r.value));return !rows.length?<p className="text-sm text-slate-500">No sales in this period.</p>:<div className="space-y-3 max-h-80 overflow-y-auto">{rows.map((r,n)=><div key={n}><div className="flex justify-between text-xs mb-1 gap-3"><span>{r.label}</span><strong>{money(r.value)}</strong></div><div className="bg-orange-50 rounded-full h-3"><div className="bg-brand rounded-full h-3" style={{width:`${Math.max(0,r.value/max*100)}%`}}/></div></div>)}</div>;}
