import { z } from 'zod';

// This bridge mirrors the order as POS/KDS/Captain/Restaurant Admin already
// agreed on it locally - unlike payments' createPaymentOrderSchema, there is no
// MenuSnapshotItem-equivalent cloud menu for the general order domain yet
// (packages/database/src/schema.ts's menu tables are local-only), so the
// totals the device sends are trusted as-is. This is an operational mirror
// for cross-device visibility, not a payment-authoritative record.
// All money is in paise (integers).
export const syncedOrderItemSchema = z.object({
  externalItemId: z.string().min(1),
  menuItemId: z.string().max(128).optional(),
  name: z.string().min(1),
  quantity: z.number().int().min(1).max(999),
  unitPrice: z.number().int().min(0),
  modifiers: z.array(z.string()).default([]),
  /** What was chosen and what each choice cost when the order was placed (paise). Never recalculated from today's menu. */
  modifierDetails: z
    .array(z.object({ optionName: z.string(), priceDelta: z.number().int(), optionId: z.string().max(128).optional(), groupId: z.string().max(128).optional(), groupName: z.string().max(200).optional() }))
    .optional(),
  /** The pricing configuration the line was ordered with. */
  snapshot: z
    .object({
      menuVersion: z.number().int().optional(),
      basePrice: z.number().int().optional(),
      taxGroupId: z.string().max(128).optional(),
      taxRateBp: z.number().int().optional(),
      taxInclusive: z.boolean().optional(),
      lineTax: z.number().int().optional()
    })
    .optional(),
  kitchenStatus: z.string().optional(),
  /** Raised by a deliberate step backwards (a recall) or a cancellation, so it beats older copies (see order-merge.ts). */
  statusRev: z.number().int().min(0).max(1_000_000).optional(),
  /** 'COURSE_1' | 'COURSE_2' | 'COURSE_3': which part of the meal the dish belongs to. */
  course: z.string().max(16).optional(),
  cancelReason: z.string().max(120).optional(),
  /** paise: what the dish was worth before it was cancelled (the line itself drops to zero). */
  cancelledAmount: z.number().int().min(0).optional(),
  cancelledBy: z.string().max(120).optional(),
  cancelledAt: z.string().max(40).optional(),
  /** The seat (or guest number) the dish was taken for. */
  seat: z.number().int().min(1).max(99).optional(),
  /** When the dish was sent to the kitchen and when the cook marked it done (ISO times). */
  sentAt: z.string().max(40).optional(),
  readyAt: z.string().max(40).optional(),
  kitchenStation: z.string().max(64).optional(),
  specialInstructions: z.string().max(500).optional(),
  lineTotal: z.number().int().min(0)
});

export const orderSyncMetaSchema = z
  .object({
    kitchenPriority: z.enum(['NORMAL', 'URGENT']).optional(),
    kitchenPriorityRev: z.number().int().min(1).max(1_000_000).optional(),
    kitchenPriorityChangeId: z.string().uuid().optional(),
    orderNumber: z.string().max(64).optional(),
    tokenNumber: z.string().max(32).optional(),
    cashierName: z.string().max(120).optional(),
    captainName: z.string().max(120).optional(),
    /** When the table asked for the bill, and the captain's split-by-seat note. Stored on the order, merged key by key. */
    billRequestedAt: z.string().max(40).optional(),
    billSplitNote: z.string().max(200).optional(),
    customerName: z.string().max(120).optional(),
    customerPhone: z.string().max(32).optional(),
    guestCount: z.number().int().min(0).max(1000).optional(),
    createdAt: z.string().optional(),
    sourceType: z.string().max(32).optional(),
    acceptedBy: z.string().max(64).optional(),
    /** A counter device (POS / POS Admin) deliberately correcting an order's state, e.g. re-opening a wrongly completed order. */
    statusCorrection: z.boolean().optional(),
    /** Signed proof of who was signed in on the terminal / which manager approved (see StaffSessionService). Verified, then dropped. */
    staffSession: z.string().max(1200).optional(),
    approvalSession: z.string().max(1200).optional(),
    businessDayId: z.string().max(64).optional(),
    paymentTransactionId: z.string().max(128).optional(),
    refundAmountPaise: z.number().int().min(0).optional(),
    tenderedAmountPaise: z.number().int().optional(),
    paymentSplits: z.array(z.object({ method: z.string().max(32), amountPaise: z.number().int() })).optional(),
    cgstPaise: z.number().int().optional(),
    sgstPaise: z.number().int().optional(),
    roundOffPaise: z.number().int().optional(),
    serviceChargePaise: z.number().int().optional(),
    tipPaise: z.number().int().optional()
  })
  .strip();

export const orderSyncEventSchema = z.object({
  /** Unique per mutation, generated by the device (see newEventId). The server applies each eventId exactly once. */
  eventId: z.string().min(1).max(128).optional(),
  /** Correlates this order's journey across devices and server logs; defaults to the order id. */
  traceId: z.string().min(1).max(128).optional(),
  externalOrderId: z.string().min(1).max(64),
  orderType: z.string().min(1).max(32),
  status: z.string().min(1).max(32),
  tableId: z.string().max(64).optional(),
  tableLabel: z.string().max(64).optional(),
  items: z.array(syncedOrderItemSchema).min(1).max(200),
  subtotal: z.number().int().min(0),
  taxAmount: z.number().int().min(0),
  discountAmount: z.number().int().min(0).default(0),
  totalAmount: z.number().int().min(0),
  notes: z.string().max(2000).optional(),
  paymentStatus: z.string().max(32).optional(),
  paymentMethod: z.string().max(32).optional(),
  meta: orderSyncMetaSchema.optional(),
  updatedAt: z.string().datetime(),
  /**
   * The syncVersion of this order the device last saw. When it is older than the server's, another device changed the order
   * since: the server keeps its own header (totals, table, notes, type), still merges items, and flags the order for review.
   */
  baseSyncVersion: z.number().int().min(0).optional()
});

// The outer request only checks that events is a list. Each event is validated
// on its own inside OrderSyncService, so ONE malformed order is reported as an
// error for that order and never blocks the rest of the batch (it used to
// reject the whole request, and the device retried the same batch forever).
export const pushOrderSyncSchema = z.object({
  events: z.array(z.unknown()).min(1).max(100)
});

export type OrderSyncEventDto = z.infer<typeof orderSyncEventSchema>;
export type PushOrderSyncDto = z.infer<typeof pushOrderSyncSchema>;
